### ISSUE TITLE
Incompatible with sideways environment

### ISSUE THREAD

**Issue by dalcde** [hoodmane/spectralsequences#11]
If we put a spectral sequence in a `sideways` environment from the `rotating`
package, it complains that the x range is too large, even thought it is
actually fine.

**Comment by hoodmane** [comment]
A simple solution to this is to say `\SseqErrorToWarning{range-overflow}`. Not the most discoverable I guess.

**Comment by dalcde** [comment]
I have that but it pollutes the log and also I can't rely on it to tell me what the right scale to use is

**Comment by hoodmane** [comment]
Do you want a command that says "for the rest of this scope we are landscape"? Maybe that would be the best thing, and I guess we can also use an environment hook to automatically issue it in the sideways environment.

**Comment by dalcde** [comment]
Of course it would be better if it were automatic, but something manual
would be very helpful in the time being.

**Comment by hoodmane** [comment]
Okay I will define three commands: `\SseqRangeCheckStandard`, `\SseqRangeCheckSideways`, and `\SseqRangeCheckOff`. Then I can do `\AtBeginEnvironment{sideways}{\SseqRangeCheckSideways}`.

**Comment by hoodmane** [comment]
Closed by #14.

**Comment by dalcde** [comment]
This currently doesn't work when the sseq is defined via sseqdata, e.g. 

```latex
\documentclass{article}

\usepackage{rotating}
\usepackage{spectralsequences}

\begin{document}
  \begin{sseqdata}[name = foo]
    \class(0,0)
    \class(17,9)
  \end{sseqdata}
  \begin{sideways}
    \printpage[name = foo]
  \end{sideways}
\end{document}
```

Specfying `range check sideways` in either the `sseqdata` and `printpage` does not work.

**Comment by hoodmane** [comment]
Oh wait, your test still doesn't work.

**Comment by hoodmane** [comment]
Okay, now I think the logic here makes sense.
