### ISSUE TITLE
Latest CTAN version incompatible with ShareLatex

### ISSUE THREAD

**Issue by alexandred** [hoodmane/spectralsequences#2]
The most up to date version of `spectralsequences` that is available on CTAN (v1.2.0) is incompatible with ShareLatex. I circumvented this issue by simply downloading the latest source from this git repository and uploading it for ShareLatex to use instead of the one that is obtained by default from CTAN.

Perhaps an update to CTAN's stashed version is in order?

Great work with this package by the way, I can see it becoming as useful to me as tikzcd is!

**Comment by hoodmane** [comment]
What do you mean that it is incompatible with ShareLatex? What happens when you try to use it?

**Comment by hoodmane** [comment]
Okay so the problem is that ShareLatex has spectralsequences 1.0 which is incompatible with an update to xparse that happened since then. I will email their support folks and ask them to update the package.

**Comment by alexandred** [comment]
Thanks for the swift reply. I didn't realise the ShareLatex caches the packages - I thought they grabbed them directly from CTAN when they were updated. Thanks for getting in contact with them.

**Comment by hoodmane** [comment]
The response is that it won't be fixed for a while:

Hi,

Thank you for getting in touch about this, sorry that the most recent package is not installed on the servers. ShareLaTeX tracks TeXLive Stable, updating all the packages only about once a year to prevent conflicts, so unfortunately we can't update individual packages separately. However, the newer version can be used in any project by uploading the .sty file to the root directory. Hope this helps. 

Kind regards,
Harriet
ShareLaTeX support
