### ISSUE TITLE
`totalxmargin` and `totalymargin` errors

### ISSUE THREAD

**Issue by alexandred** [hoodmane/spectralsequences#3]
When trying to draw a single page of a rather simple spectral sequence which is provided with the arguments `axes type=center`, `xrange` and `yrange` together with classes that are out of bounds, I get the following errors:

```
Missing number, treated as zero.

<to be read again> 
                   \sseq@totalxmargin 
l.19     \end{sseqpage}
```

```
Illegal unit of measure (pt inserted).

<to be read again> 
                   \sseq@totalxmargin 
l.19     \end{sseqpage}
```

and similarly for `totalymargin`. A minimal example is as follows:

```
\documentclass{article}
\usepackage{spectralsequences}
\begin{document}

\begin{center}
    \begin{sseqdata}[name = basic, xscale = 1.5, yscale=1.5,
    cohomological Serre grading, classes = {draw = none }, axes type=center,  x range = {-1}{4}, y range = {-1}{4}]
    \end{sseqdata}
    \begin{sseqpage}[name=basic, page = 0]
        \foreach \x in {-15,...,15}
            \foreach \y in {-15,...,15}{
            \class["E_{\page}^{\x,\y}"](\x,\y)
            }
            \foreach \x in {-4,...,6}
            \foreach \y in {-4,...,6}{
                \d\page(\x,\y)
        }
    \end{sseqpage}
\end{center}

\end{document}
```

I have taken the liberty of publishing this exampleon my ShareLatex account for ease of viewing: https://www.sharelatex.com/9384197184dfpjvctcxxby. Perhaps I am misunderstanding how one should go about typesetting such a spectral sequence?

Note also that in this example, the negatively graded objects in the spectral sequence seem to have a larger than normal vertical bounding box. I am also not sure if this is a bug or not.

This error occurs when compiling with ShareLatex.  I have not tried another compiler/parser but I don't see a reason why this error should be compiler related.

**Comment by hoodmane** [comment]
The most recent commit is not quite stable -- in particular, `axes type = center` is broken. Try checking out commit
adcf4fb24fccccc8bcc3bcedbe2bbcacc4950955  "Minor cleanup for sseqmacromakers.code.tex"
for the most recent stable version. If that doesn't work for some reason, then commit
3fa0752da581e254c609059b300880adbedcd617 "Update version number to 1.2.0 and submited to CTAN."
is exactly the same as the one on CTAN.

**Comment by alexandred** [comment]
Great, the first commit fixed the errors. There still appears to be an issue with the bounding box on the negatively graded classes though. I am not 100% sure if I am misunderstanding something with regards to that.

**Comment by hoodmane** [comment]
The problem is that the nodes are circles, and circles get taller when they get wider. Saying "classes=rectangle" should fix it.

**Comment by alexandred** [comment]
That did the trick, thanks!
